CREATE DATABASE project_customer_behavior;
USE project_customer_behavior;
SELECT * FROM customer LIMIT 10;

-- Q.1) What is the total revenue generated by Male vs Female customers?
SELECT gender, SUM(purchase_amount) AS revenue FROM customer
GROUP BY gender;


-- Q.2) Which customer used a discount but still spent more than than the avg purchase amt?
SELECT customer_id, gender, category, purchase_amount FROM customer
WHERE purchase_amount > (SELECT AVG(purchase_amount) FROM customer) and discount_applied = "Yes";


-- Q.3) Which are top 5 product with highest average review rating?
SELECT item_purchased, ROUND(AVG(CAST(review_rating AS DECIMAL(10,2))), 2) AS "avg product rating" FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;


-- Q.4) Compare the avg purchase amt b/w the standard & express shipping.
SELECT shipping_type, ROUND(AVG(purchase_amount),2) AS "avg purchase amt" FROM customer
WHERE shipping_type IN ("Express", "Standard")
GROUP BY shipping_type;


-- Q.5) Do subscribed customer spend more? Compare the avg spent & total revenue
-- b/w subscribers & non-subscribers.
SELECT subscription_status,
	COUNT(customer_id) AS "total customers",
    ROUND(AVG(purchase_amount),2) AS "average_spent",
    ROUND(SUM(purchase_amount),2) AS "total_revenue"
FROM customer
GROUP BY subscription_status
ORDER BY average_spent, total_revenue DESC;


-- Q.6) Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
	ROUND((SUM(CASE
				WHEN discount_applied = "Yes" THEN 1 ELSE 0
			END) / COUNT(*)) * 100,2) AS purchase_percentage
FROM customer
GROUP BY item_purchased
ORDER BY purchase_percentage DESC
LIMIT 5;


-- Q.7) Segment customers into New, Returning, Loyal based on their total number
-- of pevious purchases, & show the count of each segment.
WITH customer_type AS(
	SELECT customer_id, previous_purchases,
		CASE
			WHEN previous_purchases = 1 THEN "New"
            WHEN previous_purchases BETWEEN 2 AND 10 THEN "Returning"
            ELSE "Loyal"
		END AS customer_segment
	FROM customer
)

SELECT customer_segment, COUNT(*) AS "number of customers" FROM customer_type
GROUP BY customer_segment;


-- Q.8) Are customer who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) AS "repeat_buyers" FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q.9) What is the revenue contribution by each age group?
SELECT age_group, SUM(purchase_amount) AS "revenue_generated" FROM customer
GROUP BY age_group
ORDER BY revenue_generated DESC; 














